### ISSUE TITLE
If the input is deleted (empty string), a StringIndexOutOfBoundsException is thrown

### ISSUE THREAD

**Issue by provi-dominik** [vaadin-miki/super-fields#284]
I use the SuperBigDecimalField for example inside a gridpro component. To be more precise, I use this field as a customfield inside a gridpro component. 
If I delete the input of this SuperBigDecimalField (empty string), a StringIndexOutOfBoundsException is thrown. You find a part of the stack trace here:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at org.vaadin.miki.superfields.numbers.SuperBigDecimalField.parseRawValue(SuperBigDecimalField.java:145)
	at org.vaadin.miki.superfields.numbers.SuperBigDecimalField.parseRawValue(SuperBigDecimalField.java:19)
	at org.vaadin.miki.superfields.numbers.AbstractSuperNumberField.generateModelValue(AbstractSuperNumberField.java:403)
	at org.vaadin.miki.superfields.numbers.AbstractSuperNumberField.generateModelValue(AbstractSuperNumberField.java:46)
	at com.vaadin.flow.component.customfield.CustomField.updateValue(CustomField.java:107)
	at com.vaadin.flow.component.customfield.CustomField.lambda$new$360380dc$1(CustomField.java:74)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:441)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:441)

**Comment by vaadin-miki** [comment]
thanks for reporting the issue... silly me, I was assuming that the method will never be called with an empty string, and guess what, it was

anyway, fixed; it will be released about a week after Vaadin 14.5 is out, as I will also update Vaadin version
